### ISSUE TITLE
1.1 Migration script

### ISSUE THREAD

**Issue by barrykooij** [license-wp/license-wp#24]
For 1.1 I introduced an expiry type so license expiration can also be set in months and years (instead of only days). This changes the DB key `_license_expiry_days` to `_license_expiry_amount` and `_license_expiry_type`.

Write migration script that updates these keys

**Comment by barrykooij** [comment]
Look into if this is still needed. I manually updated my sites, not even sure how many other people are using this.

**Comment by jom** [comment]
I manually updated our site as well.

**Comment by barrykooij** [comment]
Ok closing this. This plugin needs proper versioning.
