### ISSUE TITLE
Subscription renewals might happen after license expires

### ISSUE THREAD

**Issue by jom** [license-wp/license-wp#32]
Licenses might be flagged as expired before the subscription is automatically renewed.

We could add a 24-hour buffer in the code below for all licenses _or_ treat subscription licenses differently and either just give the buffer to them or check to see if the subscription is active and scheduled for renewal today.

https://github.com/license-wp/license-wp/blob/master/src/License/License.php#L152-L160

**Comment by barrykooij** [comment]
Yeah I ran into this as well. I think it would be good to give everyone a 24 hour buffer. Worst thing is people can update 24 hours after their license has expired, not a big problem imo.
